// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SalasReuniaoApi.Data;

#nullable disable

namespace SalasReuniaoApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260101000000_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("SalasReuniaoApi.Models.SalaReuniao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PossuiProjetor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SalasReuniao");
                });
#pragma warning restore 612, 618
        }
    }
}
